### ISSUE TITLE
ошибка скрипта

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book.Packages#54]
user@user-Nitro-AN515-43:~/l4y/pkg$ node tools/setSizeAndCheckSum.js
child_process.js:674
    throw err;
    ^

Error: Command failed: curl -L https://download.savannah.gnu.org/releases/acl/acl-2.3.1.tar.xz --output downloads/acl-2.3.1.tar.xz --silent
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at /home/user/l4y/Linux4Yourself.Book.Packages/tools/setSizeAndCheckSum.js:23:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/user/l4y/Linux4Yourself.Book.Packages/tools/setSizeAndCheckSum.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  status: 23,
  signal: null,
  output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
  pid: 4146,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(0) [Uint8Array] []
}
user@user-Nitro-AN515-43:~/l4y/pkg$ node --version
v12.21.0

**Comment by avmaisak** [comment]
а сама команда отрабатывает? 

``curl -L https://download.savannah.gnu.org/releases/acl/acl-2.3.1.tar.xz --output downloads/acl-2.3.1.tar.xz --silent``

**Comment by makpif** [comment]
да, все норм
